"""empty message

Revision ID: a86b0bc20174
Revises: 51cd06e49072
Create Date: 2023-11-01 15:49:35.342553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a86b0bc20174'
down_revision = '51cd06e49072'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blogs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uploaded_on', sa.Date(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blogs', schema=None) as batch_op:
        batch_op.drop_column('uploaded_on')

    # ### end Alembic commands ###
